apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: my_namespace_ssv
  labels:
    app: nodeapp
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - port: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
  namespace: my_namespace_ssv
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: us.icr.io/my_namespace_ssv/nodeapp
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: default-us-icr-io
